### ISSUE TITLE
Tweaking ktistec's CSS when using Docker

### ISSUE THREAD

**Issue by ghost** [toddsundsted/ktistec#69]
I'm successfully running a ktistec container using the provided Docker run command, but can't figure out how to tweak the site's CSS with either of the mounted volumes.

Is this possible?

**Comment by toddsundsted** [comment]
@es9o i can't speak to the docker piece, but generally if you edit any of the javascript or css/less styling you need to rebuild the assets: `npm run build --production`

**Comment by JayVii** [comment]
For #17 I edited `/app/public/3rd/semantic-2.4.1.min.css` within the container and simply added my custom CSS to the end of that file. If you mount the `/app` or `/app/public` directory to your host, you can also keep the content in container restarts. Either way, it would be nice to have an empty `custom.css` somewhere, which you can hot-edit and which is loaded as last style file by the frontend.

**Comment by JayVii** [comment]
Another addition:

In my [`ktistec-tweaks`](https://src.jayvii.de/pub/ktistec-tweaks) repository, I also have a little description on how to include custom CSS within docker-containers.

For this, I decided to write custom rules in their own CSS file and push them to the container in the `/app/public/3rd/` directory. I then add a section to the `semantic-2.4.1.min.css file that loads my custom rules. However, the custom rules need to be called **before** any other rule is defined, i.e. it needs to be at the top of `semantic-2.4.1.min.css`.

Let's assume your container's name is `ltistec` and you wrote you curstom rules into the local file `custom.css`:
```bash
docker cp ./custom.css ktistec:/app/public/3rd/custom.css
docker exec -ti ktistec sh -c "
    echo \"@import url('custom.css');\" > /app/public/3rd/tmp && \
    cat /app/public/3rd/semantic*.css >> /app/public/3rd/tmp && \
    mv /app/public/3rd/tmp /app/public/3rd/semantic-*.min.css
"
```

You can find more infos about that in the repository linked above. It also contains a nifty custom CSS ruleset for automatic bright/dark mode (See: #17).

I suppose with @toddsundsted's answer https://github.com/toddsundsted/ktistec/issues/69#issuecomment-1478678163 and my comments above this issue is solved?

**Comment by toddsundsted** [comment]
> Either way, it would be nice to have an empty custom.css somewhere

would this be best implemented as literally a file named custom.css, or could it also be some css that's stored in the database and added to every page (easier to customize on the fly without rebuilding anything)?

another alternative is to edit src/assets/css/main.less which is used to generate the application-specific css, but it does use [less](https://lesscss.org/) instead of pure css. is that an option?

**Comment by JayVii** [comment]
I think either way has pro's and con's:

- `custom.css`: Super easy to implement (just need to reference an additional css file), allows instant changes on-the-fly (which is nice if you want to tinker) BUT requires the user to make changes on the backend side, i.e. literally changing files on disk
- `main.less`: "Cleaner" way, does not need any changes to ktistec whatsoever, BUT requires rebuild(?) and is a bit more technical. IMO nice for permanent changes, but not so good for tinkering
-  CSS stored in DB: super convenient for the user as it could be handled from within the ktistec frontend (see example screenshot below on how [miniflux](https://miniflux.app/) implements it), basically all advantages from `custom.css` BUT requires a lot more implementation effort in ktistec

![Bildschirmfoto vom 2024-08-05 12-19-12](https://github.com/user-attachments/assets/9fd6cc92-b744-4837-86ae-ee4b0e360caf)

**Comment by JayVii** [comment]
@toddsundsted I think this is fixed since release [v2.4.14](https://github.com/toddsundsted/ktistec/blob/main/CHANGELOG.md#v2414).

For future reference and others who stumble upon this: In docker, it is sufficient to mount the `/app/public/themes` directory from the container to your host. [Here](https://src.jayvii.de/pub/ktistec-tweaks/file/docker/docker-compose.yaml.html) is a docker-compose file, that (among other things) does exactly that:
```yaml
services:
  # ktistec: https://github.com/toddsundsted/ktistec
  ktistec:
    # Use pre-built image: https://github.com/toddsundsted/ktistec/pkgs/container/ktistec
    image: ghcr.io/toddsundsted/ktistec:latest
    # container name
    container_name: ktistec
    # always restart upon failures
    restart: unless-stopped
    # bind to local port 3000
    ports:
      - 3000:3000
    # mount volumes for db and uploads so they survive restarts
    volumes:
      - /var/www/ktistec/db:/db
      - /var/www/ktistec/uploads:/uploads
      - /var/www/ktistec/themes:/app/public/themes
    environment:
      - LIBRETRANSLATE_API_KEY="${LIBRETRANSLATE_API_KEY:-}"
      - DEEPL_API_KEY="${DEEPL_API_KEY:-}"
```

Afterwards, you can simply drop your custom CSS into any file within `/var/www/ktistec/themes`
