### ISSUE TITLE
Images that show correctly on the editor are not scaled appropriately on the actual post.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#84]
It seems that the images are not scaled correctly in the timeline.

What it looks like when pasting the image in the editor.

![image](https://github.com/toddsundsted/ktistec/assets/70410/dea2c60f-c930-43e9-b8a8-369280cdaed9)

What it looks like when viewing in the time line.

![image](https://github.com/toddsundsted/ktistec/assets/70410/195c6bc0-2025-4667-a455-241f48806444)

What it looks at a mastodon timeline

![image](https://github.com/toddsundsted/ktistec/assets/70410/eae1ae36-6350-41a4-80da-a99edd58894c)

It would be great if the image width is similar to how it was shown when editing.

**Comment by toddsundsted** [comment]
i'm not super enthusiastic about how the presentation looks on either ktistec or mastodon—in the feed, the image window is a fixed size and long or wide posts end up clipped in unattractive ways. maybe the thing to do here is a server setting that controls this—though there will always be pathological cases that are just going to look bad (10000x 100 pixels).

**Comment by JayVii** [comment]
The semantic UI sets the CSS for the images in the timeline as:
```css
.ui.feed > .event img.extra.image {
  width: 100%;
}
```

which results in the clipping of images with too much height. Regarding images that are too wide, semantic UI sets this:
```css
.ui.feed img.extra.image, .ui.feed video.extra.video {
  height: 375px;
}
```



It looks a lot better if this was used instead:
```css
.ui.feed > .event img.extra.image, .ui.feed > .event img.extra.video {
  width: auto;
  margin-left: auto;
  margin-right: auto;
}
.ui.feed img.extra.image, .ui.feed video.extra.video {
  height: auto;
}
```

Although there probably should be **some** width and height limit, particularly for smaller screens unless you want edge-cases that are really awkward to navigate or overflow

**Comment by JayVii** [comment]
I did some CSS dabbling and come up with [this](https://src.jayvii.de/pub/ktistec-tweaks/file/css/attachments.css.html):

```css
/* Try to avoid image and video clipping in feed */
.ui.feed > .event img.extra.image,
.ui.feed > .event video.extra.video
{
    width: 100%;
    height: auto;
    max-height: 800px;
}
```

This will prevent clipping in most cases, unless the posted image is very tall.

Additionally, if images have the same background as the ktistec ui (for example screenshots), it can be hard to realize where the image ends and the post starts. for this, i added some borders around image and video attachments:

```css
/* Add Image and Video Borders */
img.ui.extra.attachment.image,
.extra.media img.ui.attachment.image,
video.ui.extra.attachment.video,
.extra.media video.ui.attachment.video
{
    border-style: solid;
    border-width: 1px;
    border-color: #808080;
}
```

I am not sure, whether there should be subjective changes like this in ktistec directly? After all, it is easy enough to hack them into it afterwards.
